apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}


buildscript {
    dependencies {
        classpath 'io.fabric.tools:gradle:1.30.0'
    }

    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
//    dependencies {
//        classpath 'com.google.gms:google-services:3.2.1'
//    }
}

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'

    defaultConfig {
        applicationId "com.appoxee.example"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {


        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }

        debug {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5c59a56fd39ce9.45048743\""
            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"5c59a56fd39ce9.45048743\""
            buildConfigField "String", "CEP_URL", "\"https://jamie-test.shortest-route.com\""
            buildConfigField "String", "APP_ID", "\"263176\""
            buildConfigField "String", "TENANT_ID", "\"55\""

            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        frankfart {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5af2cdeb8ed080.27210061\""
        }
        virginia {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5af2cdeb8ed080.27210061\""

        }


    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
    }

    lintOptions {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation('androidx.recyclerview:recyclerview:1.0.0')
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation project(':sdk')
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.5@aar') {
        transitive = true;
    }

    implementation('com.google.firebase:firebase-messaging:20.0.0')

    implementation 'com.google.firebase:firebase-analytics:17.1.0'

    androidTestImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    implementation ('com.pixplicity.easyprefs:library:1.9.0')


}
apply plugin: 'com.google.gms.google-services'
