apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.appdistribution'

buildscript {
    dependencies {
    }

    repositories {
        google()
        jcenter()
    }
//    dependencies {
//        classpath 'com.google.gms:google-services:3.2.1'
//    }
}

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
def _glideVersion = safeExtGet("glideVersion", "4.12.0")

android {
    compileSdkVersion 29
    buildToolsVersion '29.0.2'

    defaultConfig {
        applicationId "com.appoxee.example"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

    }
    buildTypes {


        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            buildConfigField "String", "SDK_KEY", "\"5fd76d903c2247.21400126\""
            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
            buildConfigField "String", "CEP_URL", "\"\""
            buildConfigField "String", "APP_ID", "\"264115\""
            buildConfigField "String", "TENANT_ID", "\"33\""
            buildConfigField "String", "SERVER_INDEX", "\"TEST\""

        }

        debug {
            signingConfig signingConfigs.debug

            buildConfigField "String", "SDK_KEY", "\"17448d4c6f75f4.75830828\""
            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"785651527831\""
            buildConfigField "String", "CEP_URL", "\"https://jamie.g.shortest-route.com\""
            buildConfigField "String", "APP_ID", "\"106633\""
            buildConfigField "String", "TENANT_ID", "\"5963\""
            buildConfigField "String", "SERVER_INDEX", "\"L3\""
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            firebaseAppDistribution {
                releaseNotesFile = "release_notes_appoxee.txt"
                testersFile = "testers_appoxee.txt"
            }
        }

//        staging11 {
//            initWith debug
//            versionNameSuffix "_staging11"
//
//            buildConfigField "String", "SDK_KEY", "\"5e7b515d8fea59.04107963\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie-test.shortest-route.com\""
//            buildConfigField "String", "APP_ID", "\"263868\""
//            buildConfigField "String", "TENANT_ID", "\"33\""
//            buildConfigField "String", "SERVER_INDEX", "\"TEST\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//        envtest55 {
//            initWith debug
//            versionNameSuffix "_test55"
//
//            buildConfigField "String", "SDK_KEY", "\"17444e65fd55f4.55856011\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie-qa.shortest-route.com\""
//            buildConfigField "String", "APP_ID", "\"4\""
//            buildConfigField "String", "TENANT_ID", "\"55\""
//            buildConfigField "String", "SERVER_INDEX", "\"TEST_55\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//        l3demo {
//            initWith debug
//            versionNameSuffix "_l3demo"
//
//            buildConfigField "String", "SDK_KEY", "\"5e7d0c232cac94.79084190\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie.h.shortest-route.com/charon\""
//            buildConfigField "String", "APP_ID", "\"106620\""
//            buildConfigField "String", "TENANT_ID", "\"17037\""
//            buildConfigField "String", "SERVER_INDEX", "\"EMC\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//
//        p10tech {
//            initWith debug
//            versionNameSuffix "_p10tech"
//
//            buildConfigField "String", "SDK_KEY", "\"5e7d071d8e0e96.88418708\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie.c.shortest-route.com/charon\""
//            buildConfigField "String", "APP_ID", "\"110108\""
//            buildConfigField "String", "TENANT_ID", "\"60211\""
//            buildConfigField "String", "SERVER_INDEX", "\"EMC_US\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//
//        emcTech {
//            initWith debug
//            versionNameSuffix "_emcTech"
//
//            buildConfigField "String", "SDK_KEY", "\"17448ecbd4d5f4.30607346\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie.h.shortest-route.com/charon\""
//            buildConfigField "String", "APP_ID", "\"106639\""
//            buildConfigField "String", "TENANT_ID", "\"20053\""
//            buildConfigField "String", "SERVER_INDEX", "\"EMC\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//
//        l3tech {
//            initWith debug
//            versionNameSuffix "_l3tech"
//
//            buildConfigField "String", "SDK_KEY", "\"17448d4c6f75f4.75830828\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie.g.shortest-route.com/charon\""
//            buildConfigField "String", "APP_ID", "\"106633\""
//            buildConfigField "String", "TENANT_ID", "\"5963\""
//            buildConfigField "String", "SERVER_INDEX", "\"L3\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
//        metrics2 {
//            initWith debug
//            versionNameSuffix "_metrics2"
//
//            buildConfigField "String", "SDK_KEY", "\"174682119b35f5.31842504\""
//            buildConfigField "String", "GOOGLE_PROJECT_ID", "\"1028993954364\""
//            buildConfigField "String", "CEP_URL", "\"https://jamie.c.shortest-route.com\""
//            buildConfigField "String", "APP_ID", "\"110275\""
//            buildConfigField "String", "TENANT_ID", "\"60000\""
//            buildConfigField "String", "SERVER_INDEX", "\"EMC_US\""
//
//            firebaseAppDistribution {
//                releaseNotesFile = "release_notes_appoxee.txt"
//                testersFile = "testers_appoxee.txt"
//            }
//        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
    }

    lintOptions {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation('androidx.recyclerview:recyclerview:1.0.0')
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation project(':sdk')

    implementation('com.google.firebase:firebase-messaging:20.0.0')

    implementation 'com.google.firebase:firebase-analytics:17.1.0'
    api ('com.google.android.gms:play-services-location:16.0.0')

    // Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'

    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    androidTestImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:rules:1.2.0'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation "com.github.bumptech.glide:glide:${_glideVersion}"
    annotationProcessor "com.github.bumptech.glide:compiler:${_glideVersion}"
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.google.android.material:material:1.0.0'
    implementation('com.pixplicity.easyprefs:library:1.9.0')
}
apply plugin: 'com.google.gms.google-services'

task publishToTesters {
    dependsOn 'assembleStaging11'
//    dependsOn 'assembleEnvtest55'
//    dependsOn 'assembleL3demo'
//    dependsOn 'assembleP10tech'
//    dependsOn 'assembleEmcTech'
//    dependsOn 'assembleL3tech'
//    dependsOn 'assembleMetrics2'
    dependsOn 'appDistributionUploadStaging11'
//    dependsOn 'appDistributionUploadEnvtest55'
//    dependsOn 'appDistributionUploadL3demo'
//    dependsOn 'appDistributionUploadP10tech'
//    dependsOn 'appDistributionUploadEmcTech'
//    dependsOn 'appDistributionUploadL3tech'
//    dependsOn 'appDistributionUploadMetrics2'
}
