apply plugin: 'com.android.application'

buildscript {
    repositories {
        jcenter()
    }
//    dependencies {
//        classpath 'com.google.gms:google-services:3.0.0'
//    }
}

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.appoxee.example"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }

        debug {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5af2cdeb8ed080.27210061\""
            buildConfigField "String", "CEP_URL", "\"https://jamie-test.shortest-route.com\""
            buildConfigField "String", "APP_ID", "\"262317\""
            buildConfigField "String", "TENANT_ID", "\"55\""
        }

        frankfart {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5af2cdeb8ed080.27210061\""

        }
        virginia {
            signingConfig signingConfigs.debug
            buildConfigField "String", "SDK_KEY", "\"5af2cdeb8ed080.27210061\""

        }



    }
    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'LICENSE.txt'
    }

    lintOptions {
        abortOnError false
    }

}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation ('com.google.android.gms:play-services-gcm:15.0.1')
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.google.code.gson:gson:2.8.0'
    implementation project(':sdk')
}
