#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Jun 29 18:35:41 CEST 2018
apiSecret=77fb4ea3af427621af9405ae35ae09c4640afa15f8c3251341cb6e1fe65ee5c0
